// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

library CurrencyXchgSegment {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "wrilya", name: "CurrencyXchgSegm", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x74627772696c7961000000000000000043757272656e6379586368675365676d);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0080040020202020000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (uint256)
  Schema constant _keySchema = Schema.wrap(0x002001001f000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint256, uint256, uint256, uint256)
  Schema constant _valueSchema = Schema.wrap(0x008004001f1f1f1f000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "index";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](4);
    fieldNames[0] = "balanceStart";
    fieldNames[1] = "balanceEnd";
    fieldNames[2] = "raise";
    fieldNames[3] = "normalized";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get balanceStart.
   */
  function getBalanceStart(uint256 index) internal view returns (uint256 balanceStart) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(index));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get balanceStart.
   */
  function _getBalanceStart(uint256 index) internal view returns (uint256 balanceStart) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(index));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set balanceStart.
   */
  function setBalanceStart(uint256 index, uint256 balanceStart) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(index));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((balanceStart)), _fieldLayout);
  }

  /**
   * @notice Set balanceStart.
   */
  function _setBalanceStart(uint256 index, uint256 balanceStart) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(index));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((balanceStart)), _fieldLayout);
  }

  /**
   * @notice Get balanceEnd.
   */
  function getBalanceEnd(uint256 index) internal view returns (uint256 balanceEnd) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(index));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get balanceEnd.
   */
  function _getBalanceEnd(uint256 index) internal view returns (uint256 balanceEnd) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(index));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set balanceEnd.
   */
  function setBalanceEnd(uint256 index, uint256 balanceEnd) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(index));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((balanceEnd)), _fieldLayout);
  }

  /**
   * @notice Set balanceEnd.
   */
  function _setBalanceEnd(uint256 index, uint256 balanceEnd) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(index));

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((balanceEnd)), _fieldLayout);
  }

  /**
   * @notice Get raise.
   */
  function getRaise(uint256 index) internal view returns (uint256 raise) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(index));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get raise.
   */
  function _getRaise(uint256 index) internal view returns (uint256 raise) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(index));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set raise.
   */
  function setRaise(uint256 index, uint256 raise) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(index));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((raise)), _fieldLayout);
  }

  /**
   * @notice Set raise.
   */
  function _setRaise(uint256 index, uint256 raise) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(index));

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((raise)), _fieldLayout);
  }

  /**
   * @notice Get normalized.
   */
  function getNormalized(uint256 index) internal view returns (uint256 normalized) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(index));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get normalized.
   */
  function _getNormalized(uint256 index) internal view returns (uint256 normalized) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(index));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set normalized.
   */
  function setNormalized(uint256 index, uint256 normalized) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(index));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((normalized)), _fieldLayout);
  }

  /**
   * @notice Set normalized.
   */
  function _setNormalized(uint256 index, uint256 normalized) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(index));

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((normalized)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(
    uint256 index
  ) internal view returns (uint256 balanceStart, uint256 balanceEnd, uint256 raise, uint256 normalized) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(index));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(
    uint256 index
  ) internal view returns (uint256 balanceStart, uint256 balanceEnd, uint256 raise, uint256 normalized) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(index));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(uint256 index, uint256 balanceStart, uint256 balanceEnd, uint256 raise, uint256 normalized) internal {
    bytes memory _staticData = encodeStatic(balanceStart, balanceEnd, raise, normalized);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(index));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(uint256 index, uint256 balanceStart, uint256 balanceEnd, uint256 raise, uint256 normalized) internal {
    bytes memory _staticData = encodeStatic(balanceStart, balanceEnd, raise, normalized);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(index));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  ) internal pure returns (uint256 balanceStart, uint256 balanceEnd, uint256 raise, uint256 normalized) {
    balanceStart = (uint256(Bytes.getBytes32(_blob, 0)));

    balanceEnd = (uint256(Bytes.getBytes32(_blob, 32)));

    raise = (uint256(Bytes.getBytes32(_blob, 64)));

    normalized = (uint256(Bytes.getBytes32(_blob, 96)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (uint256 balanceStart, uint256 balanceEnd, uint256 raise, uint256 normalized) {
    (balanceStart, balanceEnd, raise, normalized) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(uint256 index) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(index));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(uint256 index) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(index));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    uint256 balanceStart,
    uint256 balanceEnd,
    uint256 raise,
    uint256 normalized
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(balanceStart, balanceEnd, raise, normalized);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint256 balanceStart,
    uint256 balanceEnd,
    uint256 raise,
    uint256 normalized
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(balanceStart, balanceEnd, raise, normalized);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(uint256 index) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(index));

    return _keyTuple;
  }
}
