// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

library CurrencyTuning {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "wrilya", name: "CurrencyTuning", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x74627772696c7961000000000000000043757272656e637954756e696e670000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x00a0050020202020200000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of ()
  Schema constant _keySchema = Schema.wrap(0x0000000000000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint256, uint256, uint256, uint256, uint256)
  Schema constant _valueSchema = Schema.wrap(0x00a005001f1f1f1f1f0000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](0);
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](5);
    fieldNames[0] = "maxSupply";
    fieldNames[1] = "xchgFeeBuy";
    fieldNames[2] = "xchgFeeSell";
    fieldNames[3] = "xchgSegment";
    fieldNames[4] = "xchgNonce";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get maxSupply.
   */
  function getMaxSupply() internal view returns (uint256 maxSupply) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get maxSupply.
   */
  function _getMaxSupply() internal view returns (uint256 maxSupply) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set maxSupply.
   */
  function setMaxSupply(uint256 maxSupply) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((maxSupply)), _fieldLayout);
  }

  /**
   * @notice Set maxSupply.
   */
  function _setMaxSupply(uint256 maxSupply) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((maxSupply)), _fieldLayout);
  }

  /**
   * @notice Get xchgFeeBuy.
   */
  function getXchgFeeBuy() internal view returns (uint256 xchgFeeBuy) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get xchgFeeBuy.
   */
  function _getXchgFeeBuy() internal view returns (uint256 xchgFeeBuy) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set xchgFeeBuy.
   */
  function setXchgFeeBuy(uint256 xchgFeeBuy) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((xchgFeeBuy)), _fieldLayout);
  }

  /**
   * @notice Set xchgFeeBuy.
   */
  function _setXchgFeeBuy(uint256 xchgFeeBuy) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((xchgFeeBuy)), _fieldLayout);
  }

  /**
   * @notice Get xchgFeeSell.
   */
  function getXchgFeeSell() internal view returns (uint256 xchgFeeSell) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get xchgFeeSell.
   */
  function _getXchgFeeSell() internal view returns (uint256 xchgFeeSell) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set xchgFeeSell.
   */
  function setXchgFeeSell(uint256 xchgFeeSell) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((xchgFeeSell)), _fieldLayout);
  }

  /**
   * @notice Set xchgFeeSell.
   */
  function _setXchgFeeSell(uint256 xchgFeeSell) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((xchgFeeSell)), _fieldLayout);
  }

  /**
   * @notice Get xchgSegment.
   */
  function getXchgSegment() internal view returns (uint256 xchgSegment) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get xchgSegment.
   */
  function _getXchgSegment() internal view returns (uint256 xchgSegment) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set xchgSegment.
   */
  function setXchgSegment(uint256 xchgSegment) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((xchgSegment)), _fieldLayout);
  }

  /**
   * @notice Set xchgSegment.
   */
  function _setXchgSegment(uint256 xchgSegment) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((xchgSegment)), _fieldLayout);
  }

  /**
   * @notice Get xchgNonce.
   */
  function getXchgNonce() internal view returns (uint256 xchgNonce) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get xchgNonce.
   */
  function _getXchgNonce() internal view returns (uint256 xchgNonce) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set xchgNonce.
   */
  function setXchgNonce(uint256 xchgNonce) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((xchgNonce)), _fieldLayout);
  }

  /**
   * @notice Set xchgNonce.
   */
  function _setXchgNonce(uint256 xchgNonce) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((xchgNonce)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get()
    internal
    view
    returns (uint256 maxSupply, uint256 xchgFeeBuy, uint256 xchgFeeSell, uint256 xchgSegment, uint256 xchgNonce)
  {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get()
    internal
    view
    returns (uint256 maxSupply, uint256 xchgFeeBuy, uint256 xchgFeeSell, uint256 xchgSegment, uint256 xchgNonce)
  {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    uint256 maxSupply,
    uint256 xchgFeeBuy,
    uint256 xchgFeeSell,
    uint256 xchgSegment,
    uint256 xchgNonce
  ) internal {
    bytes memory _staticData = encodeStatic(maxSupply, xchgFeeBuy, xchgFeeSell, xchgSegment, xchgNonce);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    uint256 maxSupply,
    uint256 xchgFeeBuy,
    uint256 xchgFeeSell,
    uint256 xchgSegment,
    uint256 xchgNonce
  ) internal {
    bytes memory _staticData = encodeStatic(maxSupply, xchgFeeBuy, xchgFeeSell, xchgSegment, xchgNonce);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (uint256 maxSupply, uint256 xchgFeeBuy, uint256 xchgFeeSell, uint256 xchgSegment, uint256 xchgNonce)
  {
    maxSupply = (uint256(Bytes.getBytes32(_blob, 0)));

    xchgFeeBuy = (uint256(Bytes.getBytes32(_blob, 32)));

    xchgFeeSell = (uint256(Bytes.getBytes32(_blob, 64)));

    xchgSegment = (uint256(Bytes.getBytes32(_blob, 96)));

    xchgNonce = (uint256(Bytes.getBytes32(_blob, 128)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  )
    internal
    pure
    returns (uint256 maxSupply, uint256 xchgFeeBuy, uint256 xchgFeeSell, uint256 xchgSegment, uint256 xchgNonce)
  {
    (maxSupply, xchgFeeBuy, xchgFeeSell, xchgSegment, xchgNonce) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    uint256 maxSupply,
    uint256 xchgFeeBuy,
    uint256 xchgFeeSell,
    uint256 xchgSegment,
    uint256 xchgNonce
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(maxSupply, xchgFeeBuy, xchgFeeSell, xchgSegment, xchgNonce);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint256 maxSupply,
    uint256 xchgFeeBuy,
    uint256 xchgFeeSell,
    uint256 xchgSegment,
    uint256 xchgNonce
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(maxSupply, xchgFeeBuy, xchgFeeSell, xchgSegment, xchgNonce);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple() internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    return _keyTuple;
  }
}
