// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

library LedgerTuning {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "wrilya", name: "LedgerTuning", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x74627772696c796100000000000000004c656467657254756e696e6700000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x00a0050020202020200000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of ()
  Schema constant _keySchema = Schema.wrap(0x0000000000000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint256, uint256, uint256, uint256, uint256)
  Schema constant _valueSchema = Schema.wrap(0x00a005001f1f1f1f1f0000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](0);
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](5);
    fieldNames[0] = "baseDebit";
    fieldNames[1] = "maxDebit";
    fieldNames[2] = "maxStake";
    fieldNames[3] = "maxUnstake";
    fieldNames[4] = "timeToUnstake";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get baseDebit.
   */
  function getBaseDebit() internal view returns (uint256 baseDebit) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get baseDebit.
   */
  function _getBaseDebit() internal view returns (uint256 baseDebit) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set baseDebit.
   */
  function setBaseDebit(uint256 baseDebit) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((baseDebit)), _fieldLayout);
  }

  /**
   * @notice Set baseDebit.
   */
  function _setBaseDebit(uint256 baseDebit) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((baseDebit)), _fieldLayout);
  }

  /**
   * @notice Get maxDebit.
   */
  function getMaxDebit() internal view returns (uint256 maxDebit) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get maxDebit.
   */
  function _getMaxDebit() internal view returns (uint256 maxDebit) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set maxDebit.
   */
  function setMaxDebit(uint256 maxDebit) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((maxDebit)), _fieldLayout);
  }

  /**
   * @notice Set maxDebit.
   */
  function _setMaxDebit(uint256 maxDebit) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((maxDebit)), _fieldLayout);
  }

  /**
   * @notice Get maxStake.
   */
  function getMaxStake() internal view returns (uint256 maxStake) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get maxStake.
   */
  function _getMaxStake() internal view returns (uint256 maxStake) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set maxStake.
   */
  function setMaxStake(uint256 maxStake) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((maxStake)), _fieldLayout);
  }

  /**
   * @notice Set maxStake.
   */
  function _setMaxStake(uint256 maxStake) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((maxStake)), _fieldLayout);
  }

  /**
   * @notice Get maxUnstake.
   */
  function getMaxUnstake() internal view returns (uint256 maxUnstake) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get maxUnstake.
   */
  function _getMaxUnstake() internal view returns (uint256 maxUnstake) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set maxUnstake.
   */
  function setMaxUnstake(uint256 maxUnstake) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((maxUnstake)), _fieldLayout);
  }

  /**
   * @notice Set maxUnstake.
   */
  function _setMaxUnstake(uint256 maxUnstake) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((maxUnstake)), _fieldLayout);
  }

  /**
   * @notice Get timeToUnstake.
   */
  function getTimeToUnstake() internal view returns (uint256 timeToUnstake) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get timeToUnstake.
   */
  function _getTimeToUnstake() internal view returns (uint256 timeToUnstake) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set timeToUnstake.
   */
  function setTimeToUnstake(uint256 timeToUnstake) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((timeToUnstake)), _fieldLayout);
  }

  /**
   * @notice Set timeToUnstake.
   */
  function _setTimeToUnstake(uint256 timeToUnstake) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((timeToUnstake)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get()
    internal
    view
    returns (uint256 baseDebit, uint256 maxDebit, uint256 maxStake, uint256 maxUnstake, uint256 timeToUnstake)
  {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get()
    internal
    view
    returns (uint256 baseDebit, uint256 maxDebit, uint256 maxStake, uint256 maxUnstake, uint256 timeToUnstake)
  {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    uint256 baseDebit,
    uint256 maxDebit,
    uint256 maxStake,
    uint256 maxUnstake,
    uint256 timeToUnstake
  ) internal {
    bytes memory _staticData = encodeStatic(baseDebit, maxDebit, maxStake, maxUnstake, timeToUnstake);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    uint256 baseDebit,
    uint256 maxDebit,
    uint256 maxStake,
    uint256 maxUnstake,
    uint256 timeToUnstake
  ) internal {
    bytes memory _staticData = encodeStatic(baseDebit, maxDebit, maxStake, maxUnstake, timeToUnstake);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (uint256 baseDebit, uint256 maxDebit, uint256 maxStake, uint256 maxUnstake, uint256 timeToUnstake)
  {
    baseDebit = (uint256(Bytes.getBytes32(_blob, 0)));

    maxDebit = (uint256(Bytes.getBytes32(_blob, 32)));

    maxStake = (uint256(Bytes.getBytes32(_blob, 64)));

    maxUnstake = (uint256(Bytes.getBytes32(_blob, 96)));

    timeToUnstake = (uint256(Bytes.getBytes32(_blob, 128)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  )
    internal
    pure
    returns (uint256 baseDebit, uint256 maxDebit, uint256 maxStake, uint256 maxUnstake, uint256 timeToUnstake)
  {
    (baseDebit, maxDebit, maxStake, maxUnstake, timeToUnstake) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    uint256 baseDebit,
    uint256 maxDebit,
    uint256 maxStake,
    uint256 maxUnstake,
    uint256 timeToUnstake
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(baseDebit, maxDebit, maxStake, maxUnstake, timeToUnstake);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint256 baseDebit,
    uint256 maxDebit,
    uint256 maxStake,
    uint256 maxUnstake,
    uint256 timeToUnstake
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(baseDebit, maxDebit, maxStake, maxUnstake, timeToUnstake);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple() internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    return _keyTuple;
  }
}
