// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

library MPDutchInfo {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "wrilya", name: "MPDutchInfo", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x74627772696c796100000000000000004d504475746368496e666f0000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0080040020202020000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32)
  Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint256, uint256, uint256, uint256)
  Schema constant _valueSchema = Schema.wrap(0x008004001f1f1f1f000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "auctionId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](4);
    fieldNames[0] = "startsAt";
    fieldNames[1] = "endsAt";
    fieldNames[2] = "startingPrice";
    fieldNames[3] = "discountRate";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get startsAt.
   */
  function getStartsAt(bytes32 auctionId) internal view returns (uint256 startsAt) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get startsAt.
   */
  function _getStartsAt(bytes32 auctionId) internal view returns (uint256 startsAt) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set startsAt.
   */
  function setStartsAt(bytes32 auctionId, uint256 startsAt) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((startsAt)), _fieldLayout);
  }

  /**
   * @notice Set startsAt.
   */
  function _setStartsAt(bytes32 auctionId, uint256 startsAt) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((startsAt)), _fieldLayout);
  }

  /**
   * @notice Get endsAt.
   */
  function getEndsAt(bytes32 auctionId) internal view returns (uint256 endsAt) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get endsAt.
   */
  function _getEndsAt(bytes32 auctionId) internal view returns (uint256 endsAt) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set endsAt.
   */
  function setEndsAt(bytes32 auctionId, uint256 endsAt) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((endsAt)), _fieldLayout);
  }

  /**
   * @notice Set endsAt.
   */
  function _setEndsAt(bytes32 auctionId, uint256 endsAt) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((endsAt)), _fieldLayout);
  }

  /**
   * @notice Get startingPrice.
   */
  function getStartingPrice(bytes32 auctionId) internal view returns (uint256 startingPrice) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get startingPrice.
   */
  function _getStartingPrice(bytes32 auctionId) internal view returns (uint256 startingPrice) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set startingPrice.
   */
  function setStartingPrice(bytes32 auctionId, uint256 startingPrice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((startingPrice)), _fieldLayout);
  }

  /**
   * @notice Set startingPrice.
   */
  function _setStartingPrice(bytes32 auctionId, uint256 startingPrice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((startingPrice)), _fieldLayout);
  }

  /**
   * @notice Get discountRate.
   */
  function getDiscountRate(bytes32 auctionId) internal view returns (uint256 discountRate) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get discountRate.
   */
  function _getDiscountRate(bytes32 auctionId) internal view returns (uint256 discountRate) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set discountRate.
   */
  function setDiscountRate(bytes32 auctionId, uint256 discountRate) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((discountRate)), _fieldLayout);
  }

  /**
   * @notice Set discountRate.
   */
  function _setDiscountRate(bytes32 auctionId, uint256 discountRate) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((discountRate)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(
    bytes32 auctionId
  ) internal view returns (uint256 startsAt, uint256 endsAt, uint256 startingPrice, uint256 discountRate) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(
    bytes32 auctionId
  ) internal view returns (uint256 startsAt, uint256 endsAt, uint256 startingPrice, uint256 discountRate) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    bytes32 auctionId,
    uint256 startsAt,
    uint256 endsAt,
    uint256 startingPrice,
    uint256 discountRate
  ) internal {
    bytes memory _staticData = encodeStatic(startsAt, endsAt, startingPrice, discountRate);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    bytes32 auctionId,
    uint256 startsAt,
    uint256 endsAt,
    uint256 startingPrice,
    uint256 discountRate
  ) internal {
    bytes memory _staticData = encodeStatic(startsAt, endsAt, startingPrice, discountRate);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  ) internal pure returns (uint256 startsAt, uint256 endsAt, uint256 startingPrice, uint256 discountRate) {
    startsAt = (uint256(Bytes.getBytes32(_blob, 0)));

    endsAt = (uint256(Bytes.getBytes32(_blob, 32)));

    startingPrice = (uint256(Bytes.getBytes32(_blob, 64)));

    discountRate = (uint256(Bytes.getBytes32(_blob, 96)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (uint256 startsAt, uint256 endsAt, uint256 startingPrice, uint256 discountRate) {
    (startsAt, endsAt, startingPrice, discountRate) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 auctionId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 auctionId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    uint256 startsAt,
    uint256 endsAt,
    uint256 startingPrice,
    uint256 discountRate
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(startsAt, endsAt, startingPrice, discountRate);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint256 startsAt,
    uint256 endsAt,
    uint256 startingPrice,
    uint256 discountRate
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(startsAt, endsAt, startingPrice, discountRate);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 auctionId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    return _keyTuple;
  }
}
