// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

// Import user types
import { Auction } from "./../common.sol";

library MPInfo {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "wrilya", name: "MPInfo", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x74627772696c796100000000000000004d50496e666f00000000000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0041030020200100000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32)
  Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (bytes32, bytes32, uint8)
  Schema constant _valueSchema = Schema.wrap(0x004103005f5f0000000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "auctionId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](3);
    fieldNames[0] = "entityId";
    fieldNames[1] = "seller";
    fieldNames[2] = "auctionType";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get entityId.
   */
  function getEntityId(bytes32 auctionId) internal view returns (bytes32 entityId) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (bytes32(_blob));
  }

  /**
   * @notice Get entityId.
   */
  function _getEntityId(bytes32 auctionId) internal view returns (bytes32 entityId) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (bytes32(_blob));
  }

  /**
   * @notice Set entityId.
   */
  function setEntityId(bytes32 auctionId, bytes32 entityId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((entityId)), _fieldLayout);
  }

  /**
   * @notice Set entityId.
   */
  function _setEntityId(bytes32 auctionId, bytes32 entityId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((entityId)), _fieldLayout);
  }

  /**
   * @notice Get seller.
   */
  function getSeller(bytes32 auctionId) internal view returns (bytes32 seller) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (bytes32(_blob));
  }

  /**
   * @notice Get seller.
   */
  function _getSeller(bytes32 auctionId) internal view returns (bytes32 seller) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (bytes32(_blob));
  }

  /**
   * @notice Set seller.
   */
  function setSeller(bytes32 auctionId, bytes32 seller) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((seller)), _fieldLayout);
  }

  /**
   * @notice Set seller.
   */
  function _setSeller(bytes32 auctionId, bytes32 seller) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((seller)), _fieldLayout);
  }

  /**
   * @notice Get auctionType.
   */
  function getAuctionType(bytes32 auctionId) internal view returns (Auction auctionType) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return Auction(uint8(bytes1(_blob)));
  }

  /**
   * @notice Get auctionType.
   */
  function _getAuctionType(bytes32 auctionId) internal view returns (Auction auctionType) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return Auction(uint8(bytes1(_blob)));
  }

  /**
   * @notice Set auctionType.
   */
  function setAuctionType(bytes32 auctionId, Auction auctionType) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked(uint8(auctionType)), _fieldLayout);
  }

  /**
   * @notice Set auctionType.
   */
  function _setAuctionType(bytes32 auctionId, Auction auctionType) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked(uint8(auctionType)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(bytes32 auctionId) internal view returns (bytes32 entityId, bytes32 seller, Auction auctionType) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(bytes32 auctionId) internal view returns (bytes32 entityId, bytes32 seller, Auction auctionType) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(bytes32 auctionId, bytes32 entityId, bytes32 seller, Auction auctionType) internal {
    bytes memory _staticData = encodeStatic(entityId, seller, auctionType);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(bytes32 auctionId, bytes32 entityId, bytes32 seller, Auction auctionType) internal {
    bytes memory _staticData = encodeStatic(entityId, seller, auctionType);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  ) internal pure returns (bytes32 entityId, bytes32 seller, Auction auctionType) {
    entityId = (Bytes.getBytes32(_blob, 0));

    seller = (Bytes.getBytes32(_blob, 32));

    auctionType = Auction(uint8(Bytes.getBytes1(_blob, 64)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (bytes32 entityId, bytes32 seller, Auction auctionType) {
    (entityId, seller, auctionType) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 auctionId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 auctionId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(bytes32 entityId, bytes32 seller, Auction auctionType) internal pure returns (bytes memory) {
    return abi.encodePacked(entityId, seller, auctionType);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    bytes32 entityId,
    bytes32 seller,
    Auction auctionType
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(entityId, seller, auctionType);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 auctionId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    return _keyTuple;
  }
}
