// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

library MPListInfo {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "wrilya", name: "MPListInfo", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x74627772696c796100000000000000004d504c697374496e666f000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0020010020000000000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32)
  Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint256)
  Schema constant _valueSchema = Schema.wrap(0x002001001f000000000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "auctionId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](1);
    fieldNames[0] = "price";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get price.
   */
  function getPrice(bytes32 auctionId) internal view returns (uint256 price) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get price.
   */
  function _getPrice(bytes32 auctionId) internal view returns (uint256 price) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get price.
   */
  function get(bytes32 auctionId) internal view returns (uint256 price) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get price.
   */
  function _get(bytes32 auctionId) internal view returns (uint256 price) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set price.
   */
  function setPrice(bytes32 auctionId, uint256 price) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((price)), _fieldLayout);
  }

  /**
   * @notice Set price.
   */
  function _setPrice(bytes32 auctionId, uint256 price) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((price)), _fieldLayout);
  }

  /**
   * @notice Set price.
   */
  function set(bytes32 auctionId, uint256 price) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((price)), _fieldLayout);
  }

  /**
   * @notice Set price.
   */
  function _set(bytes32 auctionId, uint256 price) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((price)), _fieldLayout);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 auctionId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 auctionId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(uint256 price) internal pure returns (bytes memory) {
    return abi.encodePacked(price);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(uint256 price) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(price);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 auctionId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    return _keyTuple;
  }
}
