// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

library MPPennyInfo {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "wrilya", name: "MPPennyInfo", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x74627772696c796100000000000000004d5050656e6e79496e666f0000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0080040020202020000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32)
  Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint256, bytes32, uint256, uint256)
  Schema constant _valueSchema = Schema.wrap(0x008004001f5f1f1f000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "auctionId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](4);
    fieldNames[0] = "endsAt";
    fieldNames[1] = "bidder";
    fieldNames[2] = "currentPrice";
    fieldNames[3] = "total";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get endsAt.
   */
  function getEndsAt(bytes32 auctionId) internal view returns (uint256 endsAt) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get endsAt.
   */
  function _getEndsAt(bytes32 auctionId) internal view returns (uint256 endsAt) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set endsAt.
   */
  function setEndsAt(bytes32 auctionId, uint256 endsAt) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((endsAt)), _fieldLayout);
  }

  /**
   * @notice Set endsAt.
   */
  function _setEndsAt(bytes32 auctionId, uint256 endsAt) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((endsAt)), _fieldLayout);
  }

  /**
   * @notice Get bidder.
   */
  function getBidder(bytes32 auctionId) internal view returns (bytes32 bidder) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (bytes32(_blob));
  }

  /**
   * @notice Get bidder.
   */
  function _getBidder(bytes32 auctionId) internal view returns (bytes32 bidder) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (bytes32(_blob));
  }

  /**
   * @notice Set bidder.
   */
  function setBidder(bytes32 auctionId, bytes32 bidder) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((bidder)), _fieldLayout);
  }

  /**
   * @notice Set bidder.
   */
  function _setBidder(bytes32 auctionId, bytes32 bidder) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((bidder)), _fieldLayout);
  }

  /**
   * @notice Get currentPrice.
   */
  function getCurrentPrice(bytes32 auctionId) internal view returns (uint256 currentPrice) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get currentPrice.
   */
  function _getCurrentPrice(bytes32 auctionId) internal view returns (uint256 currentPrice) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set currentPrice.
   */
  function setCurrentPrice(bytes32 auctionId, uint256 currentPrice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((currentPrice)), _fieldLayout);
  }

  /**
   * @notice Set currentPrice.
   */
  function _setCurrentPrice(bytes32 auctionId, uint256 currentPrice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((currentPrice)), _fieldLayout);
  }

  /**
   * @notice Get total.
   */
  function getTotal(bytes32 auctionId) internal view returns (uint256 total) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get total.
   */
  function _getTotal(bytes32 auctionId) internal view returns (uint256 total) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set total.
   */
  function setTotal(bytes32 auctionId, uint256 total) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((total)), _fieldLayout);
  }

  /**
   * @notice Set total.
   */
  function _setTotal(bytes32 auctionId, uint256 total) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((total)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(
    bytes32 auctionId
  ) internal view returns (uint256 endsAt, bytes32 bidder, uint256 currentPrice, uint256 total) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(
    bytes32 auctionId
  ) internal view returns (uint256 endsAt, bytes32 bidder, uint256 currentPrice, uint256 total) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(bytes32 auctionId, uint256 endsAt, bytes32 bidder, uint256 currentPrice, uint256 total) internal {
    bytes memory _staticData = encodeStatic(endsAt, bidder, currentPrice, total);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(bytes32 auctionId, uint256 endsAt, bytes32 bidder, uint256 currentPrice, uint256 total) internal {
    bytes memory _staticData = encodeStatic(endsAt, bidder, currentPrice, total);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  ) internal pure returns (uint256 endsAt, bytes32 bidder, uint256 currentPrice, uint256 total) {
    endsAt = (uint256(Bytes.getBytes32(_blob, 0)));

    bidder = (Bytes.getBytes32(_blob, 32));

    currentPrice = (uint256(Bytes.getBytes32(_blob, 64)));

    total = (uint256(Bytes.getBytes32(_blob, 96)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (uint256 endsAt, bytes32 bidder, uint256 currentPrice, uint256 total) {
    (endsAt, bidder, currentPrice, total) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 auctionId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 auctionId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    uint256 endsAt,
    bytes32 bidder,
    uint256 currentPrice,
    uint256 total
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(endsAt, bidder, currentPrice, total);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint256 endsAt,
    bytes32 bidder,
    uint256 currentPrice,
    uint256 total
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(endsAt, bidder, currentPrice, total);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 auctionId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = auctionId;

    return _keyTuple;
  }
}
