// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

library MPTuning {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "wrilya", name: "MPTuning", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x74627772696c796100000000000000004d5054756e696e670000000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x01c00e0020202020202020202020202020200000000000000000000000000000);

  // Hex-encoded key schema of ()
  Schema constant _keySchema = Schema.wrap(0x0000000000000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint256, uint256, uint256, uint256, uint256, uint256, uint256, uint256, uint256, uint256, uint256, uint256, uint256, uint256)
  Schema constant _valueSchema = Schema.wrap(0x01c00e001f1f1f1f1f1f1f1f1f1f1f1f1f1f0000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](0);
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](14);
    fieldNames[0] = "listFee";
    fieldNames[1] = "listRake";
    fieldNames[2] = "englishFee";
    fieldNames[3] = "englishRake";
    fieldNames[4] = "englishMinTime";
    fieldNames[5] = "englishMaxTime";
    fieldNames[6] = "dutchFee";
    fieldNames[7] = "dutchRake";
    fieldNames[8] = "dutchMinTime";
    fieldNames[9] = "dutchMaxTime";
    fieldNames[10] = "pennyFee";
    fieldNames[11] = "pennyRake";
    fieldNames[12] = "pennyMinTime";
    fieldNames[13] = "pennyMaxTime";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get listFee.
   */
  function getListFee() internal view returns (uint256 listFee) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get listFee.
   */
  function _getListFee() internal view returns (uint256 listFee) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set listFee.
   */
  function setListFee(uint256 listFee) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((listFee)), _fieldLayout);
  }

  /**
   * @notice Set listFee.
   */
  function _setListFee(uint256 listFee) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((listFee)), _fieldLayout);
  }

  /**
   * @notice Get listRake.
   */
  function getListRake() internal view returns (uint256 listRake) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get listRake.
   */
  function _getListRake() internal view returns (uint256 listRake) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set listRake.
   */
  function setListRake(uint256 listRake) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((listRake)), _fieldLayout);
  }

  /**
   * @notice Set listRake.
   */
  function _setListRake(uint256 listRake) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((listRake)), _fieldLayout);
  }

  /**
   * @notice Get englishFee.
   */
  function getEnglishFee() internal view returns (uint256 englishFee) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get englishFee.
   */
  function _getEnglishFee() internal view returns (uint256 englishFee) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set englishFee.
   */
  function setEnglishFee(uint256 englishFee) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((englishFee)), _fieldLayout);
  }

  /**
   * @notice Set englishFee.
   */
  function _setEnglishFee(uint256 englishFee) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((englishFee)), _fieldLayout);
  }

  /**
   * @notice Get englishRake.
   */
  function getEnglishRake() internal view returns (uint256 englishRake) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get englishRake.
   */
  function _getEnglishRake() internal view returns (uint256 englishRake) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set englishRake.
   */
  function setEnglishRake(uint256 englishRake) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((englishRake)), _fieldLayout);
  }

  /**
   * @notice Set englishRake.
   */
  function _setEnglishRake(uint256 englishRake) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((englishRake)), _fieldLayout);
  }

  /**
   * @notice Get englishMinTime.
   */
  function getEnglishMinTime() internal view returns (uint256 englishMinTime) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get englishMinTime.
   */
  function _getEnglishMinTime() internal view returns (uint256 englishMinTime) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set englishMinTime.
   */
  function setEnglishMinTime(uint256 englishMinTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((englishMinTime)), _fieldLayout);
  }

  /**
   * @notice Set englishMinTime.
   */
  function _setEnglishMinTime(uint256 englishMinTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((englishMinTime)), _fieldLayout);
  }

  /**
   * @notice Get englishMaxTime.
   */
  function getEnglishMaxTime() internal view returns (uint256 englishMaxTime) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get englishMaxTime.
   */
  function _getEnglishMaxTime() internal view returns (uint256 englishMaxTime) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set englishMaxTime.
   */
  function setEnglishMaxTime(uint256 englishMaxTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((englishMaxTime)), _fieldLayout);
  }

  /**
   * @notice Set englishMaxTime.
   */
  function _setEnglishMaxTime(uint256 englishMaxTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((englishMaxTime)), _fieldLayout);
  }

  /**
   * @notice Get dutchFee.
   */
  function getDutchFee() internal view returns (uint256 dutchFee) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 6, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get dutchFee.
   */
  function _getDutchFee() internal view returns (uint256 dutchFee) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 6, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set dutchFee.
   */
  function setDutchFee(uint256 dutchFee) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((dutchFee)), _fieldLayout);
  }

  /**
   * @notice Set dutchFee.
   */
  function _setDutchFee(uint256 dutchFee) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((dutchFee)), _fieldLayout);
  }

  /**
   * @notice Get dutchRake.
   */
  function getDutchRake() internal view returns (uint256 dutchRake) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 7, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get dutchRake.
   */
  function _getDutchRake() internal view returns (uint256 dutchRake) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 7, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set dutchRake.
   */
  function setDutchRake(uint256 dutchRake) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 7, abi.encodePacked((dutchRake)), _fieldLayout);
  }

  /**
   * @notice Set dutchRake.
   */
  function _setDutchRake(uint256 dutchRake) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 7, abi.encodePacked((dutchRake)), _fieldLayout);
  }

  /**
   * @notice Get dutchMinTime.
   */
  function getDutchMinTime() internal view returns (uint256 dutchMinTime) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 8, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get dutchMinTime.
   */
  function _getDutchMinTime() internal view returns (uint256 dutchMinTime) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 8, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set dutchMinTime.
   */
  function setDutchMinTime(uint256 dutchMinTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 8, abi.encodePacked((dutchMinTime)), _fieldLayout);
  }

  /**
   * @notice Set dutchMinTime.
   */
  function _setDutchMinTime(uint256 dutchMinTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 8, abi.encodePacked((dutchMinTime)), _fieldLayout);
  }

  /**
   * @notice Get dutchMaxTime.
   */
  function getDutchMaxTime() internal view returns (uint256 dutchMaxTime) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 9, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get dutchMaxTime.
   */
  function _getDutchMaxTime() internal view returns (uint256 dutchMaxTime) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 9, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set dutchMaxTime.
   */
  function setDutchMaxTime(uint256 dutchMaxTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 9, abi.encodePacked((dutchMaxTime)), _fieldLayout);
  }

  /**
   * @notice Set dutchMaxTime.
   */
  function _setDutchMaxTime(uint256 dutchMaxTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 9, abi.encodePacked((dutchMaxTime)), _fieldLayout);
  }

  /**
   * @notice Get pennyFee.
   */
  function getPennyFee() internal view returns (uint256 pennyFee) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 10, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get pennyFee.
   */
  function _getPennyFee() internal view returns (uint256 pennyFee) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 10, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set pennyFee.
   */
  function setPennyFee(uint256 pennyFee) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 10, abi.encodePacked((pennyFee)), _fieldLayout);
  }

  /**
   * @notice Set pennyFee.
   */
  function _setPennyFee(uint256 pennyFee) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 10, abi.encodePacked((pennyFee)), _fieldLayout);
  }

  /**
   * @notice Get pennyRake.
   */
  function getPennyRake() internal view returns (uint256 pennyRake) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 11, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get pennyRake.
   */
  function _getPennyRake() internal view returns (uint256 pennyRake) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 11, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set pennyRake.
   */
  function setPennyRake(uint256 pennyRake) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 11, abi.encodePacked((pennyRake)), _fieldLayout);
  }

  /**
   * @notice Set pennyRake.
   */
  function _setPennyRake(uint256 pennyRake) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 11, abi.encodePacked((pennyRake)), _fieldLayout);
  }

  /**
   * @notice Get pennyMinTime.
   */
  function getPennyMinTime() internal view returns (uint256 pennyMinTime) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 12, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get pennyMinTime.
   */
  function _getPennyMinTime() internal view returns (uint256 pennyMinTime) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 12, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set pennyMinTime.
   */
  function setPennyMinTime(uint256 pennyMinTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 12, abi.encodePacked((pennyMinTime)), _fieldLayout);
  }

  /**
   * @notice Set pennyMinTime.
   */
  function _setPennyMinTime(uint256 pennyMinTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 12, abi.encodePacked((pennyMinTime)), _fieldLayout);
  }

  /**
   * @notice Get pennyMaxTime.
   */
  function getPennyMaxTime() internal view returns (uint256 pennyMaxTime) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 13, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get pennyMaxTime.
   */
  function _getPennyMaxTime() internal view returns (uint256 pennyMaxTime) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 13, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set pennyMaxTime.
   */
  function setPennyMaxTime(uint256 pennyMaxTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 13, abi.encodePacked((pennyMaxTime)), _fieldLayout);
  }

  /**
   * @notice Set pennyMaxTime.
   */
  function _setPennyMaxTime(uint256 pennyMaxTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 13, abi.encodePacked((pennyMaxTime)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get()
    internal
    view
    returns (
      uint256 listFee,
      uint256 listRake,
      uint256 englishFee,
      uint256 englishRake,
      uint256 englishMinTime,
      uint256 englishMaxTime,
      uint256 dutchFee,
      uint256 dutchRake,
      uint256 dutchMinTime,
      uint256 dutchMaxTime,
      uint256 pennyFee,
      uint256 pennyRake,
      uint256 pennyMinTime,
      uint256 pennyMaxTime
    )
  {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get()
    internal
    view
    returns (
      uint256 listFee,
      uint256 listRake,
      uint256 englishFee,
      uint256 englishRake,
      uint256 englishMinTime,
      uint256 englishMaxTime,
      uint256 dutchFee,
      uint256 dutchRake,
      uint256 dutchMinTime,
      uint256 dutchMaxTime,
      uint256 pennyFee,
      uint256 pennyRake,
      uint256 pennyMinTime,
      uint256 pennyMaxTime
    )
  {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    uint256 listFee,
    uint256 listRake,
    uint256 englishFee,
    uint256 englishRake,
    uint256 englishMinTime,
    uint256 englishMaxTime,
    uint256 dutchFee,
    uint256 dutchRake,
    uint256 dutchMinTime,
    uint256 dutchMaxTime,
    uint256 pennyFee,
    uint256 pennyRake,
    uint256 pennyMinTime,
    uint256 pennyMaxTime
  ) internal {
    bytes memory _staticData = encodeStatic(
      listFee,
      listRake,
      englishFee,
      englishRake,
      englishMinTime,
      englishMaxTime,
      dutchFee,
      dutchRake,
      dutchMinTime,
      dutchMaxTime,
      pennyFee,
      pennyRake,
      pennyMinTime,
      pennyMaxTime
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    uint256 listFee,
    uint256 listRake,
    uint256 englishFee,
    uint256 englishRake,
    uint256 englishMinTime,
    uint256 englishMaxTime,
    uint256 dutchFee,
    uint256 dutchRake,
    uint256 dutchMinTime,
    uint256 dutchMaxTime,
    uint256 pennyFee,
    uint256 pennyRake,
    uint256 pennyMinTime,
    uint256 pennyMaxTime
  ) internal {
    bytes memory _staticData = encodeStatic(
      listFee,
      listRake,
      englishFee,
      englishRake,
      englishMinTime,
      englishMaxTime,
      dutchFee,
      dutchRake,
      dutchMinTime,
      dutchMaxTime,
      pennyFee,
      pennyRake,
      pennyMinTime,
      pennyMaxTime
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (
      uint256 listFee,
      uint256 listRake,
      uint256 englishFee,
      uint256 englishRake,
      uint256 englishMinTime,
      uint256 englishMaxTime,
      uint256 dutchFee,
      uint256 dutchRake,
      uint256 dutchMinTime,
      uint256 dutchMaxTime,
      uint256 pennyFee,
      uint256 pennyRake,
      uint256 pennyMinTime,
      uint256 pennyMaxTime
    )
  {
    listFee = (uint256(Bytes.getBytes32(_blob, 0)));

    listRake = (uint256(Bytes.getBytes32(_blob, 32)));

    englishFee = (uint256(Bytes.getBytes32(_blob, 64)));

    englishRake = (uint256(Bytes.getBytes32(_blob, 96)));

    englishMinTime = (uint256(Bytes.getBytes32(_blob, 128)));

    englishMaxTime = (uint256(Bytes.getBytes32(_blob, 160)));

    dutchFee = (uint256(Bytes.getBytes32(_blob, 192)));

    dutchRake = (uint256(Bytes.getBytes32(_blob, 224)));

    dutchMinTime = (uint256(Bytes.getBytes32(_blob, 256)));

    dutchMaxTime = (uint256(Bytes.getBytes32(_blob, 288)));

    pennyFee = (uint256(Bytes.getBytes32(_blob, 320)));

    pennyRake = (uint256(Bytes.getBytes32(_blob, 352)));

    pennyMinTime = (uint256(Bytes.getBytes32(_blob, 384)));

    pennyMaxTime = (uint256(Bytes.getBytes32(_blob, 416)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  )
    internal
    pure
    returns (
      uint256 listFee,
      uint256 listRake,
      uint256 englishFee,
      uint256 englishRake,
      uint256 englishMinTime,
      uint256 englishMaxTime,
      uint256 dutchFee,
      uint256 dutchRake,
      uint256 dutchMinTime,
      uint256 dutchMaxTime,
      uint256 pennyFee,
      uint256 pennyRake,
      uint256 pennyMinTime,
      uint256 pennyMaxTime
    )
  {
    (
      listFee,
      listRake,
      englishFee,
      englishRake,
      englishMinTime,
      englishMaxTime,
      dutchFee,
      dutchRake,
      dutchMinTime,
      dutchMaxTime,
      pennyFee,
      pennyRake,
      pennyMinTime,
      pennyMaxTime
    ) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    uint256 listFee,
    uint256 listRake,
    uint256 englishFee,
    uint256 englishRake,
    uint256 englishMinTime,
    uint256 englishMaxTime,
    uint256 dutchFee,
    uint256 dutchRake,
    uint256 dutchMinTime,
    uint256 dutchMaxTime,
    uint256 pennyFee,
    uint256 pennyRake,
    uint256 pennyMinTime,
    uint256 pennyMaxTime
  ) internal pure returns (bytes memory) {
    return
      abi.encodePacked(
        listFee,
        listRake,
        englishFee,
        englishRake,
        englishMinTime,
        englishMaxTime,
        dutchFee,
        dutchRake,
        dutchMinTime,
        dutchMaxTime,
        pennyFee,
        pennyRake,
        pennyMinTime,
        pennyMaxTime
      );
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint256 listFee,
    uint256 listRake,
    uint256 englishFee,
    uint256 englishRake,
    uint256 englishMinTime,
    uint256 englishMaxTime,
    uint256 dutchFee,
    uint256 dutchRake,
    uint256 dutchMinTime,
    uint256 dutchMaxTime,
    uint256 pennyFee,
    uint256 pennyRake,
    uint256 pennyMinTime,
    uint256 pennyMaxTime
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(
      listFee,
      listRake,
      englishFee,
      englishRake,
      englishMinTime,
      englishMaxTime,
      dutchFee,
      dutchRake,
      dutchMinTime,
      dutchMaxTime,
      pennyFee,
      pennyRake,
      pennyMinTime,
      pennyMaxTime
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple() internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    return _keyTuple;
  }
}
