// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

library VMSkillsTuning {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "wrilya", name: "VMSkillsTuning", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x74627772696c79610000000000000000564d536b696c6c7354756e696e670000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x01060c0001022020202001202002202000000000000000000000000000000000);

  // Hex-encoded key schema of ()
  Schema constant _keySchema = Schema.wrap(0x0000000000000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint8, uint16, uint256, uint256, uint256, uint256, uint8, uint256, uint256, uint16, uint256, uint256)
  Schema constant _valueSchema = Schema.wrap(0x01060c0000011f1f1f1f001f1f011f1f00000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](0);
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](12);
    fieldNames[0] = "trainingFieldMaxValue";
    fieldNames[1] = "trainingFieldsMaxTotal";
    fieldNames[2] = "trainingCostBase";
    fieldNames[3] = "trainingCostPower";
    fieldNames[4] = "trainingTimeBase";
    fieldNames[5] = "trainingTimePower";
    fieldNames[6] = "abilityFieldMaxValue";
    fieldNames[7] = "abilityPointsBase";
    fieldNames[8] = "abilityPointsPower";
    fieldNames[9] = "abilityRespecMax";
    fieldNames[10] = "abilityRespecCostBase";
    fieldNames[11] = "abilityRespecCostPower";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get trainingFieldMaxValue.
   */
  function getTrainingFieldMaxValue() internal view returns (uint8 trainingFieldMaxValue) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Get trainingFieldMaxValue.
   */
  function _getTrainingFieldMaxValue() internal view returns (uint8 trainingFieldMaxValue) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Set trainingFieldMaxValue.
   */
  function setTrainingFieldMaxValue(uint8 trainingFieldMaxValue) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((trainingFieldMaxValue)), _fieldLayout);
  }

  /**
   * @notice Set trainingFieldMaxValue.
   */
  function _setTrainingFieldMaxValue(uint8 trainingFieldMaxValue) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((trainingFieldMaxValue)), _fieldLayout);
  }

  /**
   * @notice Get trainingFieldsMaxTotal.
   */
  function getTrainingFieldsMaxTotal() internal view returns (uint16 trainingFieldsMaxTotal) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint16(bytes2(_blob)));
  }

  /**
   * @notice Get trainingFieldsMaxTotal.
   */
  function _getTrainingFieldsMaxTotal() internal view returns (uint16 trainingFieldsMaxTotal) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint16(bytes2(_blob)));
  }

  /**
   * @notice Set trainingFieldsMaxTotal.
   */
  function setTrainingFieldsMaxTotal(uint16 trainingFieldsMaxTotal) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((trainingFieldsMaxTotal)), _fieldLayout);
  }

  /**
   * @notice Set trainingFieldsMaxTotal.
   */
  function _setTrainingFieldsMaxTotal(uint16 trainingFieldsMaxTotal) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((trainingFieldsMaxTotal)), _fieldLayout);
  }

  /**
   * @notice Get trainingCostBase.
   */
  function getTrainingCostBase() internal view returns (uint256 trainingCostBase) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get trainingCostBase.
   */
  function _getTrainingCostBase() internal view returns (uint256 trainingCostBase) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set trainingCostBase.
   */
  function setTrainingCostBase(uint256 trainingCostBase) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((trainingCostBase)), _fieldLayout);
  }

  /**
   * @notice Set trainingCostBase.
   */
  function _setTrainingCostBase(uint256 trainingCostBase) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((trainingCostBase)), _fieldLayout);
  }

  /**
   * @notice Get trainingCostPower.
   */
  function getTrainingCostPower() internal view returns (uint256 trainingCostPower) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get trainingCostPower.
   */
  function _getTrainingCostPower() internal view returns (uint256 trainingCostPower) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set trainingCostPower.
   */
  function setTrainingCostPower(uint256 trainingCostPower) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((trainingCostPower)), _fieldLayout);
  }

  /**
   * @notice Set trainingCostPower.
   */
  function _setTrainingCostPower(uint256 trainingCostPower) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((trainingCostPower)), _fieldLayout);
  }

  /**
   * @notice Get trainingTimeBase.
   */
  function getTrainingTimeBase() internal view returns (uint256 trainingTimeBase) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get trainingTimeBase.
   */
  function _getTrainingTimeBase() internal view returns (uint256 trainingTimeBase) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set trainingTimeBase.
   */
  function setTrainingTimeBase(uint256 trainingTimeBase) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((trainingTimeBase)), _fieldLayout);
  }

  /**
   * @notice Set trainingTimeBase.
   */
  function _setTrainingTimeBase(uint256 trainingTimeBase) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((trainingTimeBase)), _fieldLayout);
  }

  /**
   * @notice Get trainingTimePower.
   */
  function getTrainingTimePower() internal view returns (uint256 trainingTimePower) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get trainingTimePower.
   */
  function _getTrainingTimePower() internal view returns (uint256 trainingTimePower) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set trainingTimePower.
   */
  function setTrainingTimePower(uint256 trainingTimePower) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((trainingTimePower)), _fieldLayout);
  }

  /**
   * @notice Set trainingTimePower.
   */
  function _setTrainingTimePower(uint256 trainingTimePower) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((trainingTimePower)), _fieldLayout);
  }

  /**
   * @notice Get abilityFieldMaxValue.
   */
  function getAbilityFieldMaxValue() internal view returns (uint8 abilityFieldMaxValue) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 6, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Get abilityFieldMaxValue.
   */
  function _getAbilityFieldMaxValue() internal view returns (uint8 abilityFieldMaxValue) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 6, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Set abilityFieldMaxValue.
   */
  function setAbilityFieldMaxValue(uint8 abilityFieldMaxValue) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((abilityFieldMaxValue)), _fieldLayout);
  }

  /**
   * @notice Set abilityFieldMaxValue.
   */
  function _setAbilityFieldMaxValue(uint8 abilityFieldMaxValue) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((abilityFieldMaxValue)), _fieldLayout);
  }

  /**
   * @notice Get abilityPointsBase.
   */
  function getAbilityPointsBase() internal view returns (uint256 abilityPointsBase) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 7, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get abilityPointsBase.
   */
  function _getAbilityPointsBase() internal view returns (uint256 abilityPointsBase) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 7, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set abilityPointsBase.
   */
  function setAbilityPointsBase(uint256 abilityPointsBase) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 7, abi.encodePacked((abilityPointsBase)), _fieldLayout);
  }

  /**
   * @notice Set abilityPointsBase.
   */
  function _setAbilityPointsBase(uint256 abilityPointsBase) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 7, abi.encodePacked((abilityPointsBase)), _fieldLayout);
  }

  /**
   * @notice Get abilityPointsPower.
   */
  function getAbilityPointsPower() internal view returns (uint256 abilityPointsPower) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 8, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get abilityPointsPower.
   */
  function _getAbilityPointsPower() internal view returns (uint256 abilityPointsPower) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 8, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set abilityPointsPower.
   */
  function setAbilityPointsPower(uint256 abilityPointsPower) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 8, abi.encodePacked((abilityPointsPower)), _fieldLayout);
  }

  /**
   * @notice Set abilityPointsPower.
   */
  function _setAbilityPointsPower(uint256 abilityPointsPower) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 8, abi.encodePacked((abilityPointsPower)), _fieldLayout);
  }

  /**
   * @notice Get abilityRespecMax.
   */
  function getAbilityRespecMax() internal view returns (uint16 abilityRespecMax) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 9, _fieldLayout);
    return (uint16(bytes2(_blob)));
  }

  /**
   * @notice Get abilityRespecMax.
   */
  function _getAbilityRespecMax() internal view returns (uint16 abilityRespecMax) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 9, _fieldLayout);
    return (uint16(bytes2(_blob)));
  }

  /**
   * @notice Set abilityRespecMax.
   */
  function setAbilityRespecMax(uint16 abilityRespecMax) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 9, abi.encodePacked((abilityRespecMax)), _fieldLayout);
  }

  /**
   * @notice Set abilityRespecMax.
   */
  function _setAbilityRespecMax(uint16 abilityRespecMax) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 9, abi.encodePacked((abilityRespecMax)), _fieldLayout);
  }

  /**
   * @notice Get abilityRespecCostBase.
   */
  function getAbilityRespecCostBase() internal view returns (uint256 abilityRespecCostBase) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 10, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get abilityRespecCostBase.
   */
  function _getAbilityRespecCostBase() internal view returns (uint256 abilityRespecCostBase) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 10, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set abilityRespecCostBase.
   */
  function setAbilityRespecCostBase(uint256 abilityRespecCostBase) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 10, abi.encodePacked((abilityRespecCostBase)), _fieldLayout);
  }

  /**
   * @notice Set abilityRespecCostBase.
   */
  function _setAbilityRespecCostBase(uint256 abilityRespecCostBase) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 10, abi.encodePacked((abilityRespecCostBase)), _fieldLayout);
  }

  /**
   * @notice Get abilityRespecCostPower.
   */
  function getAbilityRespecCostPower() internal view returns (uint256 abilityRespecCostPower) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 11, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get abilityRespecCostPower.
   */
  function _getAbilityRespecCostPower() internal view returns (uint256 abilityRespecCostPower) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 11, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set abilityRespecCostPower.
   */
  function setAbilityRespecCostPower(uint256 abilityRespecCostPower) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 11, abi.encodePacked((abilityRespecCostPower)), _fieldLayout);
  }

  /**
   * @notice Set abilityRespecCostPower.
   */
  function _setAbilityRespecCostPower(uint256 abilityRespecCostPower) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 11, abi.encodePacked((abilityRespecCostPower)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get()
    internal
    view
    returns (
      uint8 trainingFieldMaxValue,
      uint16 trainingFieldsMaxTotal,
      uint256 trainingCostBase,
      uint256 trainingCostPower,
      uint256 trainingTimeBase,
      uint256 trainingTimePower,
      uint8 abilityFieldMaxValue,
      uint256 abilityPointsBase,
      uint256 abilityPointsPower,
      uint16 abilityRespecMax,
      uint256 abilityRespecCostBase,
      uint256 abilityRespecCostPower
    )
  {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get()
    internal
    view
    returns (
      uint8 trainingFieldMaxValue,
      uint16 trainingFieldsMaxTotal,
      uint256 trainingCostBase,
      uint256 trainingCostPower,
      uint256 trainingTimeBase,
      uint256 trainingTimePower,
      uint8 abilityFieldMaxValue,
      uint256 abilityPointsBase,
      uint256 abilityPointsPower,
      uint16 abilityRespecMax,
      uint256 abilityRespecCostBase,
      uint256 abilityRespecCostPower
    )
  {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    uint8 trainingFieldMaxValue,
    uint16 trainingFieldsMaxTotal,
    uint256 trainingCostBase,
    uint256 trainingCostPower,
    uint256 trainingTimeBase,
    uint256 trainingTimePower,
    uint8 abilityFieldMaxValue,
    uint256 abilityPointsBase,
    uint256 abilityPointsPower,
    uint16 abilityRespecMax,
    uint256 abilityRespecCostBase,
    uint256 abilityRespecCostPower
  ) internal {
    bytes memory _staticData = encodeStatic(
      trainingFieldMaxValue,
      trainingFieldsMaxTotal,
      trainingCostBase,
      trainingCostPower,
      trainingTimeBase,
      trainingTimePower,
      abilityFieldMaxValue,
      abilityPointsBase,
      abilityPointsPower,
      abilityRespecMax,
      abilityRespecCostBase,
      abilityRespecCostPower
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    uint8 trainingFieldMaxValue,
    uint16 trainingFieldsMaxTotal,
    uint256 trainingCostBase,
    uint256 trainingCostPower,
    uint256 trainingTimeBase,
    uint256 trainingTimePower,
    uint8 abilityFieldMaxValue,
    uint256 abilityPointsBase,
    uint256 abilityPointsPower,
    uint16 abilityRespecMax,
    uint256 abilityRespecCostBase,
    uint256 abilityRespecCostPower
  ) internal {
    bytes memory _staticData = encodeStatic(
      trainingFieldMaxValue,
      trainingFieldsMaxTotal,
      trainingCostBase,
      trainingCostPower,
      trainingTimeBase,
      trainingTimePower,
      abilityFieldMaxValue,
      abilityPointsBase,
      abilityPointsPower,
      abilityRespecMax,
      abilityRespecCostBase,
      abilityRespecCostPower
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (
      uint8 trainingFieldMaxValue,
      uint16 trainingFieldsMaxTotal,
      uint256 trainingCostBase,
      uint256 trainingCostPower,
      uint256 trainingTimeBase,
      uint256 trainingTimePower,
      uint8 abilityFieldMaxValue,
      uint256 abilityPointsBase,
      uint256 abilityPointsPower,
      uint16 abilityRespecMax,
      uint256 abilityRespecCostBase,
      uint256 abilityRespecCostPower
    )
  {
    trainingFieldMaxValue = (uint8(Bytes.getBytes1(_blob, 0)));

    trainingFieldsMaxTotal = (uint16(Bytes.getBytes2(_blob, 1)));

    trainingCostBase = (uint256(Bytes.getBytes32(_blob, 3)));

    trainingCostPower = (uint256(Bytes.getBytes32(_blob, 35)));

    trainingTimeBase = (uint256(Bytes.getBytes32(_blob, 67)));

    trainingTimePower = (uint256(Bytes.getBytes32(_blob, 99)));

    abilityFieldMaxValue = (uint8(Bytes.getBytes1(_blob, 131)));

    abilityPointsBase = (uint256(Bytes.getBytes32(_blob, 132)));

    abilityPointsPower = (uint256(Bytes.getBytes32(_blob, 164)));

    abilityRespecMax = (uint16(Bytes.getBytes2(_blob, 196)));

    abilityRespecCostBase = (uint256(Bytes.getBytes32(_blob, 198)));

    abilityRespecCostPower = (uint256(Bytes.getBytes32(_blob, 230)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  )
    internal
    pure
    returns (
      uint8 trainingFieldMaxValue,
      uint16 trainingFieldsMaxTotal,
      uint256 trainingCostBase,
      uint256 trainingCostPower,
      uint256 trainingTimeBase,
      uint256 trainingTimePower,
      uint8 abilityFieldMaxValue,
      uint256 abilityPointsBase,
      uint256 abilityPointsPower,
      uint16 abilityRespecMax,
      uint256 abilityRespecCostBase,
      uint256 abilityRespecCostPower
    )
  {
    (
      trainingFieldMaxValue,
      trainingFieldsMaxTotal,
      trainingCostBase,
      trainingCostPower,
      trainingTimeBase,
      trainingTimePower,
      abilityFieldMaxValue,
      abilityPointsBase,
      abilityPointsPower,
      abilityRespecMax,
      abilityRespecCostBase,
      abilityRespecCostPower
    ) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    uint8 trainingFieldMaxValue,
    uint16 trainingFieldsMaxTotal,
    uint256 trainingCostBase,
    uint256 trainingCostPower,
    uint256 trainingTimeBase,
    uint256 trainingTimePower,
    uint8 abilityFieldMaxValue,
    uint256 abilityPointsBase,
    uint256 abilityPointsPower,
    uint16 abilityRespecMax,
    uint256 abilityRespecCostBase,
    uint256 abilityRespecCostPower
  ) internal pure returns (bytes memory) {
    return
      abi.encodePacked(
        trainingFieldMaxValue,
        trainingFieldsMaxTotal,
        trainingCostBase,
        trainingCostPower,
        trainingTimeBase,
        trainingTimePower,
        abilityFieldMaxValue,
        abilityPointsBase,
        abilityPointsPower,
        abilityRespecMax,
        abilityRespecCostBase,
        abilityRespecCostPower
      );
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint8 trainingFieldMaxValue,
    uint16 trainingFieldsMaxTotal,
    uint256 trainingCostBase,
    uint256 trainingCostPower,
    uint256 trainingTimeBase,
    uint256 trainingTimePower,
    uint8 abilityFieldMaxValue,
    uint256 abilityPointsBase,
    uint256 abilityPointsPower,
    uint16 abilityRespecMax,
    uint256 abilityRespecCostBase,
    uint256 abilityRespecCostPower
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(
      trainingFieldMaxValue,
      trainingFieldsMaxTotal,
      trainingCostBase,
      trainingCostPower,
      trainingTimeBase,
      trainingTimePower,
      abilityFieldMaxValue,
      abilityPointsBase,
      abilityPointsPower,
      abilityRespecMax,
      abilityRespecCostBase,
      abilityRespecCostPower
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple() internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    return _keyTuple;
  }
}
