import Config

# ------------------------------------------------------------------------------
# Guardian Redis Setup Configurations
# ------------------------------------------------------------------------------
config :guardian_redis, :redis,
  host: "127.0.0.1",
  port: 6379,
  pool_size: 10

# Configure Faucet database
config :faucet, Faucet.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "faucet_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :faucet,
  contract: "0xad523115cd35a8d4e60b3c0953e0e0ac10418309",
  sources: %{
    # NOTE:   These faucets are for testing/debugging ONLY
    #         Never use in production as this are well known
    #         values generated from Anvil
    "0b7efe15-93fe-40fb-8533-dca5f0fe83ed" => %{
      type: :faucet,
      window_size: 24 * 60 * 60,
      drip_amount: 1_000_000_000,
      drips_per_window: 1_000_000,
      receiver_max_balance: 1_500_000_000,
      receiver_drips_per_window: 10,
      reservoir_id: "f79ea88b-f651-408b-aae7-e05b49dd54e9",
      keys: [
        %{
          # Address: 0x70997970C51812dc3A010C7d01b50e0d17dc79C8
          key: "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d",
          type: :secp256k1
        }
      ]
    },
    # This is our Faucet for Faucet account
    "f79ea88b-f651-408b-aae7-e05b49dd54e9" => %{
      type: :reservoir,
      window_size: 24 * 60 * 60,
      drip_amount: 1_000_000_000_000_000_000,
      drips_per_window: 1,
      receiver_max_balance: 500_000_000_000_000_000,
      receiver_drips_per_window: 1,
      reservoir: nil,
      keys: [
        %{
          # Address: 0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65
          key: "0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a",
          type: :secp256k1
        }
      ]
    }
  }

config :wrilya,
  faucet: "0b7efe15-93fe-40fb-8533-dca5f0fe83ed"

# Configure Account database
config :account, Account.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "account_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# Configure Wrilya database
config :wrilya, Wrilya.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "wrilya_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# Configure MUD database
config :mud, MUD.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "postgres",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  after_connect:
    {MUD.Repo, :set_search_path, ["app,public,0x8d8b6b8414e1e3dcfd4168561b9be6bd3bf6ec4b"]}

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :wrilya_web, WrilyaWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "jxp1ew7Qg2upOPTs3jmRyDKIshwRoETj5wDu1KbKwHV+GmJ6lxTUEHfT8wN5OnPR",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:wrilya_web, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:wrilya_web, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :wrilya_web, WrilyaWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/wrilya_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :wrilya_web, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

config :nostrum,
  token: System.get_env("DISCORD_TOKEN")

config :account, Account.Vault,
  ciphers: [
    default:
      {Cloak.Ciphers.AES.GCM,
       tag: "AES.GCM.V1", key: Base.decode64!("HXCdm5z61eNgUpnXObJRv94k3JnKSrnfwppyb60nz6w=")}
  ]

config :faucet, Faucet.Vault,
  ciphers: [
    default:
      {Cloak.Ciphers.AES.GCM,
       tag: "AES.GCM.V1", key: Base.decode64!("unIX0buZf2L4KucnEIQ2Az/o4yVZpn/2O42re3VSAGc=")}
  ]
