
export enum OperationEnum {
  UNKNOWN = 0,
  GAME_PAUSE,
  GAME_UNPAUSE,
  GAME_SET_ADMIN,
  GAME_SET_GM,
  GAME_SET_CURRENCY_PROXY,
  GAME_SET_ITEM_PROXY,
  GAME_SET_ENTITY_PROXY,
  GAME_SET_VOIDSMAN_CREATE_COST,
  GAME_SET_VOIDSMAN_UPGRADE_TIME_BASE,
  GAME_SET_VOIDSMAN_UPGRADE_TIME_POWER,
  GAME_SET_VOIDSMAN_UPGRADE_COST_BASE,
  GAME_SET_VOIDSMAN_UPGRADE_COST_POWER,
  GAME_SET_VOIDSMAN_MAX_STATS,
  GAME_SET_VOIDSMAN_MAX_COMPETENCY,
  ENTITY_CREATE,
  ENTITY_DESTROY,
  ENTITY_TRANSFER,
  ENTITY_UPDATE,
  VOIDSMAN_TRAIN,
  VOIDSMAN_TRAIN_CANCEL,
  VOIDSMAN_CERTIFY,
  VOIDSMAN_SET_TRAINING_REQUIREMENT,
  __LENGTH
}

export enum EntityEnum {
  UNKNOWN = 0,
  VOIDSMAN,
  SHIP,
  STATION,
  PLANET,
  SOLARSYSTEM,
  __LENGTH
}

export enum HomeEnum {
  UNKNOWN = 0,
  ICOIR,
  VREL,
  PRIME,
  MILVEA,
  SAREA,
  GRAIK,
  CHIVEN,
  AIGEA,
  __LENGTH
}

export enum FieldEnum {
  UNKNOWN = 0,
  ARMOR,
  ENGINES,
  LEADERSHIP,
  NAVIGATION,
  NEGOTIATION,
  SHIPCRAFT,
  SENSORS,
  SHIELDS,
  WEAPONS,
  __LENGTH
}

export enum AbilityEnum {
  UNKNOWN = 0,
  STRENGTH,
  PSYCHE,
  TECHNIQUE,
  INTELLIGENCE,
  FOCUS,
  ENDURANCE,
  RELEXES,
  __LENGTH
}