// SPDX-License-Identifier: GPL-3.0-or-later
//
// Copyright (C) 2024 Decentralized Consulting
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.

pragma solidity >=0.8.26;

import {BanPerm, BanTemp, VerifiedOps} from "./codegen/index.sol";
import "@openzeppelin/contracts/utils/cryptography/SignatureChecker.sol";
import "@openzeppelin/contracts/utils/cryptography/MessageHashUtils.sol";
import "./errors.sol";
import {ZERO_BYTES32, ENTITY_MASK} from "./constants.sol";

/**
 * Check it see if an account is banned.
 *
 * Requirements:
 *
 * - Only callable from a System contract that has read access to MUD storage
 *
 * @param address_ to check if it is banned
 */
function isBanned(address address_) view returns (bool) {
  return (BanTemp.getExpires(address_) >= block.timestamp)
    || BanPerm.getValue(address_);
}

/**
 * @dev A basic check if the ID was generated by the system.
 *
 * Waring:
 *
 * The inverse of `isSystemEntity` does not mean it is an account.
 *
 * Example:
 * - true == !isSystemEntity(0);
 * - false == isAccountEntity(0);
 *
 * @param id_ to check if it is an entity or an account
 */
function isSystemEntity(bytes32 id_) pure returns (bool) {
  return (ENTITY_MASK & id_) != 0;
}

/**
 * @dev A basic check if the ID is an account (address based)
 *
 * Waring:
 *
 * The inverse of `isAccountEntity` does not mean it is a system entity.
 *
 * Example:
 * - true == !isAccountEntity(0);
 * - false == isSystemEntity(0);
 *
 * @param id_ to check if it is an account
 */
function isAccountEntity(bytes32 id_) pure returns (bool) {
  return ((ENTITY_MASK & id_) == 0) && (id_ != 0);
}

/**
 * @dev Validate a signature with the system.
 *
 * NOTE:  This expects that the signature was generated using the Eth Signed
 * Message format that wraps the binary payload in a bunch of text data.  For
 * more details see: `MessageHashUtils.toEthSignedMessageHash` to see what it is
 * doing.
 *
 * @param hashedData_ The keccak256 hashed data payload
 * @param signature_ The generated signature for the hashed data
 * @param signer_ The signer of the data
 */
function isValidSignature(
  bytes32 hashedData_,
  bytes memory signature_,
  address signer_
) view returns (bool) {
  bytes32 digest = MessageHashUtils.toEthSignedMessageHash(hashedData_);
  return SignatureChecker.isValidSignatureNow(signer_, digest, signature_);
}
