// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */
enum Race {
  UNKNOWN,
  HUMAN,
  ICOIR,
  VREL,
  MILVEA,
  SAREA,
  GRAIK,
  CHIVEN
}

enum Skill {
  ARMOR,
  ENGINES,
  LEADERSHIP,
  NAVIGATION,
  NEGOTIATION,
  REPAIRS,
  SENSORS,
  SHIELDS,
  WEAPONS
}
