// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */
enum Command {
  UNKNOWN,
  PAUSE,
  RESUME
}

enum Notice {
  UNKNOWN
}

enum Actor {
  UNKNOWN,
  VOIDSMAN,
  SHIP,
  STATION,
  PLANET,
  SOLARSYSTEM,
  LOT
}

enum Knowledge {
  UNKNOWN,
  COMMAND,
  PILOT,
  WEAPONS,
  SHIELDS,
  SHIPCRAFT,
  SENSORS,
  MEDICAL
}

enum Ability {
  UNKNOWN,
  FITNESS,
  PSYCHE,
  TECHNIQUE,
  INTELLIGENCE,
  FOCUS,
  ENDURANCE,
  REFLEX
}

enum Auction {
  UNKNOWN,
  LIST,
  ENGLISH,
  DUTCH,
  PENNY
}
