// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */
enum HomeEnum {
  ICOIR,
  VREL,
  PRIME,
  MILVEA,
  SAREA,
  GRAIK,
  CHIVEN,
  AIGEA
}

enum FieldEnum {
  ARMOR,
  ENGINES,
  LEADERSHIP,
  NAVIGATION,
  NEGOTIATION,
  SHIPCRAFT,
  SENSORS,
  SHIELDS,
  WEAPONS
}

enum AbilityEnum {
  STRENGTH,
  PSYCHE,
  TECHNIQUE,
  INTELLIGENCE,
  FOCUS,
  ENDURANCE,
  RELEXES
}
