// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { GameConfig, GameConfigData } from "./tables/GameConfig.sol";
import { VerifiedOps } from "./tables/VerifiedOps.sol";
import { BanTuning } from "./tables/BanTuning.sol";
import { BanTemp } from "./tables/BanTemp.sol";
import { BanPerm } from "./tables/BanPerm.sol";
import { CommandNonce } from "./tables/CommandNonce.sol";
import { Commands } from "./tables/Commands.sol";
import { Notices } from "./tables/Notices.sol";
import { EntityNonce } from "./tables/EntityNonce.sol";
import { EntityInfo } from "./tables/EntityInfo.sol";
import { EntityBalance } from "./tables/EntityBalance.sol";
import { VMGeneralTuning } from "./tables/VMGeneralTuning.sol";
import { VMSkillsTuning } from "./tables/VMSkillsTuning.sol";
import { VMInfo } from "./tables/VMInfo.sol";
import { VMLearning } from "./tables/VMLearning.sol";
import { VMLearnReq } from "./tables/VMLearnReq.sol";
import { CurrencyConfig } from "./tables/CurrencyConfig.sol";
import { CurrencyTuning } from "./tables/CurrencyTuning.sol";
import { CurrencyXchgSegment } from "./tables/CurrencyXchgSegment.sol";
import { LedgerTuning } from "./tables/LedgerTuning.sol";
import { LedgerInfo } from "./tables/LedgerInfo.sol";
import { MPConfig } from "./tables/MPConfig.sol";
import { MPTuning } from "./tables/MPTuning.sol";
import { MPNonce } from "./tables/MPNonce.sol";
import { MPInfo } from "./tables/MPInfo.sol";
import { MPListInfo } from "./tables/MPListInfo.sol";
import { MPEnglishInfo } from "./tables/MPEnglishInfo.sol";
import { MPDutchInfo } from "./tables/MPDutchInfo.sol";
import { MPPennyInfo } from "./tables/MPPennyInfo.sol";
