// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { GameConfigTable, GameConfigTableData } from "./tables/GameConfigTable.sol";
import { NotificationIDTable } from "./tables/NotificationIDTable.sol";
import { NotificationTable } from "./tables/NotificationTable.sol";
import { CurrencyTable } from "./tables/CurrencyTable.sol";
import { EntityIdTable } from "./tables/EntityIdTable.sol";
import { EntityOwnerTable } from "./tables/EntityOwnerTable.sol";
import { EntityTypeTable } from "./tables/EntityTypeTable.sol";
import { EntityInfoTable } from "./tables/EntityInfoTable.sol";
import { EntityNameRegistryTable } from "./tables/EntityNameRegistryTable.sol";
import { EntityDescriptionTable } from "./tables/EntityDescriptionTable.sol";
import { EntityXPTable } from "./tables/EntityXPTable.sol";
import { VoidsmanTrainingTable } from "./tables/VoidsmanTrainingTable.sol";
import { VoidsmanRequirementsTable, VoidsmanRequirementsTableData } from "./tables/VoidsmanRequirementsTable.sol";
import { VoidsmanCompetencyTable } from "./tables/VoidsmanCompetencyTable.sol";
import { VoidsmanStatsTable } from "./tables/VoidsmanStatsTable.sol";
import { MarketplaceVoidsman } from "./tables/MarketplaceVoidsman.sol";
import { MarketplaceJobsBoard } from "./tables/MarketplaceJobsBoard.sol";
