// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { VoidsmenTable } from "./tables/VoidsmenTable.sol";
import { ShipTable } from "./tables/ShipTable.sol";
import { OwnedByTable } from "./tables/OwnedByTable.sol";
import { HomeTable } from "./tables/HomeTable.sol";
import { NameTable } from "./tables/NameTable.sol";
import { PortraitTable } from "./tables/PortraitTable.sol";
import { TrainingTable } from "./tables/TrainingTable.sol";
import { PersonaTable, PersonaTableData } from "./tables/PersonaTable.sol";
import { EntityCounterTable } from "./tables/EntityCounterTable.sol";
import { Counter } from "./tables/Counter.sol";
