// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IBannedSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IBannedSystem {
  function wrilya__banned(address account_) external view returns (bool status);

  function wrilya__bannedIssueTemp(address account_) external;

  function wrilya__bannedReleaseTemp(address account_) external;

  function wrilya__bannedIssuePerm(address account_) external;

  function wrilya__bannedReleasePerm(address account_) external;
}
