// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IBannedTuningSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IBannedTuningSystem {
  function wrilya__bannedTuningSet(uint256 tempTime_) external;

  function wrilya__bannedTuningSetTempTime(uint256 tempTime_) external;
}
