// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ICurrencySystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICurrencySystem {
  function wrilya__currencyMint(uint256 amount_) external payable;

  function wrilya__currencyXchgPause() external;

  function wrilya__currencyXchgRun() external;

  function wrilya__currencyXchgBuy() external payable returns (uint256);

  function wrilya__currencyXchgSell(uint256 amount_) external returns (uint256);
}
