// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ICurrencyTuningSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICurrencyTuningSystem {
  function wrilya__currencyTuningSet(uint256 maxSupply_, uint256 xchgFeeBuy_, uint256 xchgFeeSell_) external;

  function wrilya__currencyTuningSetXchgFeeBuy(uint256 fee_) external;

  function wrilya__currencyTuningSetXchgFeeSell(uint256 fee_) external;

  function wrilya__currencyTuningSetMaxSupply(uint256 amount_) external;
}
