// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IEntitySystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IEntitySystem {
  function wrilya__entityBalanceOf(bytes32 owner_) external view returns (uint256);

  function wrilya__entityOwnerOf(bytes32 entityId_) external view returns (bytes32);

  function wrilya__entityTransfer(bytes32 from_, bytes32 to_, bytes32 entityId_) external;

  function wrilya__entityTransfer(bytes32 to_, bytes32 entityId_) external;
}
