// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IGameSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IGameSystem {
  function wrilya__initialize(
    address gm_,
    address payee_,
    address gov_,
    address curProxy_,
    address itemProxy_,
    address entityProxy_
  ) external;

  function wrilya__transferGM(address gm_) external;

  function wrilya__transferGovernor(address gov_) external;

  function wrilya__transferPayee(address payee_) external;

  function wrilya__transferCurrencyProxy(address proxy_) external;

  function wrilya__transferItemProxy(address proxy_) external;

  function wrilya__transferEntityProxy(address proxy_) external;

  function wrilya__pause() external;

  function wrilya__run() external;
}
