// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IGameSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IGameSystem {
  function game__pause() external;

  function game__unpause() external;

  function game__setGM(address newGM) external;

  function game__setAdmin(address newAdmin) external;

  function game__setCurrencyProxy(address proxy) external;

  function game__setItemProxy(address proxy) external;

  function game__setGovernor(address gov) external;

  function game__setVoteToken(address token) external;

  function game__setEntityProxy(address proxy) external;

  function game__setVoidsmanCreateCost(uint256 cost) external;

  function game__setVoidsmanUpgradeTimeBase(uint256 base) external;

  function game__setVoidsmanUpgradeTimePower(uint256 power) external;

  function game__setVoidsmanUpgradeCostBase(uint256 base) external;

  function game__setVoidsmanUpgradeCostPower(uint256 power) external;

  function game__setVoidsmanMaxStats(uint8 max) external;

  function game__setVoidsmanMaxCompetency(uint8 max) external;

  function game__setStdMaxDebit(uint256 value) external;

  function game__setCollateralDebitRatio(uint256 ratio) external;

  function game__setCurrencyUnstakeTime(uint256 ratio) external;
}
