// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ILedgerSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ILedgerSystem {
  function wrilya__ledgerTokenBalanceOf(bytes32 id_) external view returns (uint256);

  function wrilya__ledgerTokenTransfer(address receiver_, uint256 amount_) external;

  function wrilya__ledgerTokenTransfer(bytes32 receiver_, uint256 amount_) external;

  function wrilya__ledgerTokenTransfer(bytes32 from_, bytes32 receiver_, uint256 amount_) external;

  function wrilya__ledgerTokenTransfer(address from_, address receiver_, uint256 amount_) external;

  function wrilya__ledgerStake(uint256 amount_) external;

  function wrilya__ledgerUnstake(uint256 amount_) external;

  function wrilya__ledgerClaim() external;

  function wrilya__ledgerPayment(uint256 amount_) external;

  function wrilya__ledgerCredit(address receiver_, uint256 amount_) external;

  function wrilya__ledgerBill(address recipient_, uint256 amount_) external;
}
