// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ILedgerTuningSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ILedgerTuningSystem {
  function wrilya__ledgerTuningSet(
    uint256 baseDebit_,
    uint256 maxDebit_,
    uint256 maxStake_,
    uint256 maxUnstake_,
    uint256 timeToUnstake_
  ) external;

  function wrilya__ledgerTuningSetBaseDebit(uint256 baseDebit_) external;

  function wrilya__ledgerTuningSetMaxDebit(uint256 maxDebit_) external;

  function wrilya__ledgerTuningSetMaxStake(uint256 maxStake_) external;

  function wrilya__ledgerTuningSetMaxUnstake(uint256 maxUnstake_) external;

  function wrilya__ledgerTuningSetTimeToUnstake(uint256 timeToUnstake_) external;
}
