// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IMarketTuningSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IMarketTuningSystem {
  function wrilya__marketTuningSet(
    uint256 listFee_,
    uint256 listRake_,
    uint256 englishFee_,
    uint256 englishRake_,
    uint256 englishMinTime_,
    uint256 englishMaxTime_,
    uint256 dutchFee_,
    uint256 dutchRake_,
    uint256 dutchMinTime_,
    uint256 dutchMaxTime_,
    uint256 pennyFee_,
    uint256 pennyRake_,
    uint256 pennyMinTime_,
    uint256 pennyMaxTime_
  ) external;

  function wrilya__marketTuningSetList(uint256 listFee_, uint256 listRake_) external;

  function wrilya__marketTuningSetEnglish(
    uint256 englishFee_,
    uint256 englishRake_,
    uint256 englishMinTime_,
    uint256 englishMaxTime_
  ) external;

  function wrilya__marketTuningSetEnglishCosts(uint256 englishFee_, uint256 englishRake_) external;

  function wrilya__marketTuningSetEnglishTimes(uint256 englishMinTime_, uint256 englishMaxTime_) external;

  function wrilya__marketTuningSetDutch(
    uint256 dutchFee_,
    uint256 dutchRake_,
    uint256 dutchMinTime_,
    uint256 dutchMaxTime_
  ) external;

  function wrilya__marketTuningSetDutchCosts(uint256 dutchFee_, uint256 dutchRake_) external;

  function wrilya__marketTuningSetDutchTimes(uint256 dutchMinTime_, uint256 dutchMaxTime_) external;

  function wrilya__marketTuningSetPenny(
    uint256 pennyFee_,
    uint256 pennyRake_,
    uint256 pennyMinTime_,
    uint256 pennyMaxTime_
  ) external;

  function wrilya__marketTuningSetPennyCosts(uint256 pennyFee_, uint256 pennyRake_) external;

  function wrilya__marketTuningSetPennyTimes(uint256 pennyMinTime_, uint256 pennyMaxTime_) external;
}
