// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IMarketSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IMarketSystem {
  function wrilya__marketPause() external;

  function wrilya__marketRun() external;

  function wrilya__marketCreateListLot(bytes32 entityId_, uint256 price_) external returns (bytes32 auctionId);

  function wrilya__marketCreateEnglishLot(
    bytes32 entityId_,
    uint256 endsIn_,
    uint256 startingPrice_
  ) external returns (bytes32 aid);

  function wrilya__marketCreateDutchLot(
    bytes32 entityId_,
    uint256 endsIn_,
    uint256 startingPrice_,
    uint256 lowestPrice_
  ) external returns (bytes32 aid);

  function wrilya__marketCreatePennyLot(bytes32 entityId_, uint256 endsIn_) external returns (bytes32 aid);

  function wrilya__marketBidLot(bytes32 auctionId_, uint256 price_) external;

  function wrilya__marketWithdrawLot(bytes32 auctionId_) external;

  function wrilya__marketClaimLot(bytes32 auctionId_) external;
}
