// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Knowledge } from "./../common.sol";

/**
 * @title IVoidsmanTuningSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IVoidsmanTuningSystem {
  function wrilya__voidsmanGeneralTuningSet(uint256 mintFee, uint256 xpMax, uint256 xpBase, uint256 xpPower) external;

  function wrilya__voidsmanSkillsTuningSet(
    uint8 trainingFieldMaxValue,
    uint16 trainingieldMaxTotal,
    uint256 trainingCostBase,
    uint256 trainingCostPower,
    uint256 trainingTimeBase,
    uint256 trainingTimePower,
    uint8 abilityFieldMaxValue,
    uint256 abilityPointsBase,
    uint256 abilityPointsPower,
    uint16 abilityRespecMax,
    uint256 abilityRespecCostBase,
    uint256 abilityRespecCostPower
  ) external;

  function wrilya__voidsmanTuningSetLearningRequirement(
    uint8 level_,
    Knowledge field_,
    uint256 xp_,
    bytes32 skills_
  ) external;

  function wrilya__voidsmanTuningSetMintFee(uint256 fee_) external;

  function wrilya__voidsmanTuningSetTrainingFieldMaxValue(uint8 value_) external;

  function wrilya__voidsmanTuningSetTrainingFieldsMaxTotal(uint16 value_) external;

  function wrilya__voidsmanTuningSetTraningCostCurve(uint256 base_, uint256 power_) external;

  function wrilya__voidsmanTuningSetTraningTimeCurve(uint256 base_, uint256 power_) external;

  function wrilya__voidsmanTuningSetAbilityFieldMaxValue(uint8 value_) external;

  function wrilya__voidsmanTuningSetAbilityRespecMax(uint16 value_) external;

  function wrilya__voidsmanTuningSetAbilityPointsCurve(uint256 base_, uint256 power_) external;

  function wrilya__voidsmanTuningSetAbilityRespecCostCurve(uint256 base_, uint256 power_) external;

  function wrilya__voidsmanTuningSetXpMax(uint256 value_) external;

  function wrilya__voidsmanTuningSetXpLevelCurve(uint256 base_, uint256 power_) external;
}
