// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IVoidsmanSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IVoidsmanSystem {
  function wrilya__voidsmanMint(bytes16 offchainRef_, bytes16 opId_, bytes memory signature_) external;

  function wrilya__voidsmanMint(bytes16 offchainRef_, bytes32 owner_) external returns (bytes32);

  function wrilya__voidsmanBurn(bytes32 entityId_) external;

  function wrilya__voidsmanAwardXP(bytes32 entityId_, uint64 amount_) external;

  function wrilya__voidsmanAwardXP(bytes32 entityId_, uint64 amount_, bytes16 opId_, bytes memory signature_) external;

  function wrilya__voidsmanRedeemXP(bytes32 entityId_, uint64 amount_, bytes16 opId_, bytes memory signature_) external;
}
