// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Ability, Knowledge } from "./../common.sol";

/**
 * @title IVoidsmanSkillsSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IVoidsmanSkillsSystem {
  function wrilya__voidsmanSkillsRespec(bytes32 entityId_) external;

  function wrilya__voidmanSkillUpgrade(bytes32 entityId_, Ability field_) external;

  function wrilya__voidsmanSkillLearn(bytes32 entityId_, Knowledge field_) external;

  function wrilya__voidsmanSkillForget(bytes32 entityId_, Knowledge field_) external;

  function wrilya__voidsmanSkillDropout(bytes32 entityId_) external;

  function wrilya__voidsmanSkillCertify(bytes32 entityId_) external;
}
