// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/codegen/interfaces/IBaseWorld.sol";

import { IBannedSystem } from "./IBannedSystem.sol";
import { IBannedTuningSystem } from "./IBannedTuningSystem.sol";
import { ICurrencySystem } from "./ICurrencySystem.sol";
import { ICurrencyTuningSystem } from "./ICurrencyTuningSystem.sol";
import { IEntitySystem } from "./IEntitySystem.sol";
import { IGameSystem } from "./IGameSystem.sol";
import { ILedgerSystem } from "./ILedgerSystem.sol";
import { ILedgerTuningSystem } from "./ILedgerTuningSystem.sol";
import { IMarketSystem } from "./IMarketSystem.sol";
import { IMarketTuningSystem } from "./IMarketTuningSystem.sol";
import { IPlanetSystem } from "./IPlanetSystem.sol";
import { IShipSystem } from "./IShipSystem.sol";
import { ISolarSystem } from "./ISolarSystem.sol";
import { IStationSystem } from "./IStationSystem.sol";
import { IVoidsmanSkillsSystem } from "./IVoidsmanSkillsSystem.sol";
import { IVoidsmanSystem } from "./IVoidsmanSystem.sol";
import { IVoidsmanTuningSystem } from "./IVoidsmanTuningSystem.sol";

/**
 * @title IWorld
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @notice This interface integrates all systems and associated function selectors
 * that are dynamically registered in the World during deployment.
 * @dev This is an autogenerated file; do not edit manually.
 */
interface IWorld is
  IBaseWorld,
  IBannedSystem,
  IBannedTuningSystem,
  ICurrencySystem,
  ICurrencyTuningSystem,
  IEntitySystem,
  IGameSystem,
  ILedgerSystem,
  ILedgerTuningSystem,
  IMarketSystem,
  IMarketTuningSystem,
  IPlanetSystem,
  IShipSystem,
  ISolarSystem,
  IStationSystem,
  IVoidsmanSkillsSystem,
  IVoidsmanSystem,
  IVoidsmanTuningSystem
{}
