[profile.default]
solc = "0.8.26"
ffi = false
fuzz_runs = 256
# optimizer = true
# optimizer_runs = 3000
via_ir = true
verbosity = 2
src = "src"
test = "test"
out = "out"
allow_paths = [
  # pnpm symlinks to the project root's node_modules
  "../../node_modules",
  # template uses linked mud packages from within the mud monorepo
  "../../../../packages",
  # projects created from this template and using linked mud packages
  "../../../mud/packages",
]
extra_output_files = [
  "abi",
  "evm.bytecode"
]

gas_reports = ["*"]

fs_permissions = [{ access = "read", path = "./"}]

[fmt]
single_line_statement_blocks = "preserve"
multiline_func_header = "params_first"
line_length = 80
tab_width = 2
number_underscore = "thousands"
override_spacing = true
wrap_comments = true

[profile.local]
eth_rpc_url = "http://localhost:8545"

[profile.test]
eth_rpc_url = "https://sepolia-rollup.arbitrum.io/rpc"

[profile.main]
eth_rpc_url = "https://sepolia-rollup.arbitrum.io/rpc"

[profile.garnet]
eth_rpc_url = "https://rpc.garnetchain.com"

[profile.redstone]
eth_rpc_url = "https://rpc.redstonechain.com"

[rpc_endpoints]
sepolia = "${GOVERNANCE_CHAIN_RPC}"
