// SPDX-License-Identifier: GPL-3.0-or-later
//
// Copyright (C) 2024 Decentralized Consulting
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
pragma solidity >=0.8.26;

// ----------------------------------------------------------------------------
// Imports
// ----------------------------------------------------------------------------

import {System} from "@latticexyz/world/src/System.sol";
import "../entity.sol";
import "../ledger.sol";
import "../utils.sol";
import "../checks.sol";
import {InvalidState, NotReady} from "../errors.sol";
import {
  EntityBalance,
  EntityInfo,
  GameConfig,
  VerifiedOps,
  VMGeneralTuning,
  VMSkillsTuning,
  VMInfo,
  VMLearning,
  VMLearnReq
} from "../codegen/index.sol";
import {Ability, Actor, Knowledge} from "../codegen/common.sol";

// ----------------------------------------------------------------------------
/**
 * @title VoidsmanSystem
 * @author Chris Jimison
 * @notice MUD.dev based smart contract for Voidsmen
 */
contract VoidsmanSystem is System {
  /**
   * @dev Create a new Crew member and assign it to the caller.  This crew
   * member
   * will have all levels set to 0.  Requires the GM to sign the payload in
   * a multi-sig fashion
   *
   * @param offchainRef_ ID to track the offchain data
   * @param opId_ Created on the server to mark this signed transaction
   * @param signature_ of the request generated by the GM
   */
  function voidsmanMint(
    bytes16 offchainRef_,
    bytes16 opId_,
    bytes memory signature_
  ) public {
    address caller = _msgSender();
    bytes32 data =
      keccak256(abi.encodePacked("voidsman_mint", caller, offchainRef_, opId_));
    //---------------------------------
    // Verification Block
    //---------------------------------
    require(GameConfig.getActive(), GameActiveState());
    require(!VerifiedOps.getProcessed(opId_), InvalidOperation());
    require(
      isValidSignature(data, signature_, GameConfig.getGm()), InvalidSignature()
    );

    //---------------------------------
    // Logic Block
    //---------------------------------
    VerifiedOps.set(opId_, true);
    _mint(offchainRef_, toBytes32(caller));
  }

  function voidsmanMint(
    bytes16 offchainRef_,
    bytes32 owner_
  ) public returns (bytes32) {
    //---------------------------------
    // Verification Block
    //---------------------------------
    require(GameConfig.getActive(), GameActiveState());
    require(GameConfig.getGm() == _msgSender(), Unauthorized());

    //---------------------------------
    // Logic Block
    //---------------------------------
    return _mint(offchainRef_, owner_);
  }

  /**
   * @dev Burn a voidsman from the system
   * @param entityId_ to delete from chain
   */
  function voidsmanBurn(bytes32 entityId_) public {
    //---------------------------------
    // Verification Block
    //---------------------------------
    require(
      EntityInfo.getOwner(entityId_) == toBytes32(_msgSender()), InvalidCaller()
    );
    require(
      EntityInfo.getActorType(entityId_) == Actor.VOIDSMAN, InvalidArgument()
    );

    //---------------------------------
    // Logic Block
    //---------------------------------
    EntityInfo.deleteRecord(entityId_);
    VMInfo.deleteRecord(entityId_);
    VMLearning.deleteRecord(entityId_);
  }

  /**
   * @dev Add XP to a given voidsman.
   * NOTE:  We are taking advantage of Solidity 0.8+ now checking for overflows
   * but this should be validated on the target chain as well
   * @param entityId_ to assign XP to
   * @param amount_ the amount of XP to give to the voidman
   */
  function voidsmanAwardXP(bytes32 entityId_, uint64 amount_) public {
    address caller = _msgSender();
    bytes32 account = toBytes32(caller);
    //---------------------------------
    // Verification Block
    //---------------------------------
    require(GameConfig.getGm() == caller);
    require(EntityInfo.getOwner(entityId_) == account, InvalidCaller());
    require(
      EntityInfo.getActorType(entityId_) == Actor.VOIDSMAN, InvalidArgument()
    );

    //---------------------------------
    // Logic Block
    //---------------------------------
    _awardXp(entityId_, amount_);
  }

  /**
   * @dev Add XP to a given voidsman using multi-sig.
   * NOTE:  We are taking advantage of Solidity 0.8+ now checking for overflows
   * but this should be validated on the target chain as well
   * @param entityId_ to assign XP to
   * @param amount_ the amount of XP to give to the voidman
   * @param opId_ operation ID to stop replay
   * @param signature_ from the GM account
   */
  function voidsmanAwardXP(
    bytes32 entityId_,
    uint64 amount_,
    bytes16 opId_,
    bytes memory signature_
  ) public {
    address caller = _msgSender();
    bytes32 data = keccak256(
      abi.encodePacked("voidsman_award_xp", entityId_, amount_, caller, opId_)
    );

    //---------------------------------
    // Verification Block
    //---------------------------------
    require(
      EntityInfo.getOwner(entityId_) == toBytes32(caller), InvalidCaller()
    );
    require(
      EntityInfo.getActorType(entityId_) == Actor.VOIDSMAN, InvalidArgument()
    );
    require(!VerifiedOps.getProcessed(opId_), InvalidOperation());
    require(
      isValidSignature(data, signature_, GameConfig.getGm()), InvalidSignature()
    );

    //---------------------------------
    // Logic Block
    //---------------------------------
    VerifiedOps.set(opId_, true);
    _awardXp(entityId_, amount_);
  }

  /**
   * @dev As part of a giveway or promotion the GM can assign out drops of
   * xp gifts that 3rd parties can choose to let players redeem.
   * @param entityId_ to assign XP to
   * @param amount_ the amount of XP to give to the voidman
   * @param opId_ operation ID to stop replay
   * @param signature_ from the GM account
   */
  function voidsmanRedeemXP(
    bytes32 entityId_,
    uint64 amount_,
    bytes16 opId_,
    bytes memory signature_
  ) public {
    address caller = _msgSender();
    bytes32 data =
      keccak256(abi.encodePacked("voidsman_redeem_xp", amount_, opId_));

    //---------------------------------
    // Verification Block
    //---------------------------------
    require(
      EntityInfo.getOwner(entityId_) == toBytes32(caller), InvalidCaller()
    );
    require(
      EntityInfo.getActorType(entityId_) == Actor.VOIDSMAN, InvalidArgument()
    );
    require(!VerifiedOps.getProcessed(opId_), InvalidOperation());
    require(
      isValidSignature(data, signature_, GameConfig.getGm()), InvalidSignature()
    );

    //---------------------------------
    // Logic Block
    //---------------------------------
    VerifiedOps.set(opId_, true);
    _awardXp(entityId_, amount_);
  }

  //---------------------------------------------------------------------------
  // Internal Functions
  //---------------------------------------------------------------------------

  function _mint(
    bytes16 offchainRef_,
    bytes32 owner_
  ) private returns (bytes32 entityId_) {
    entityId_ = Entity.newID();
    EntityInfo.set(entityId_, owner_, Actor.VOIDSMAN, offchainRef_);
    EntityBalance.set(owner_, EntityBalance.get(owner_) + 1);
    VMInfo.set(entityId_, bytes32(0), 0, 0);

    // Add on debit to the Ledger
    Ledger.bill(owner_, VMGeneralTuning.getMintFee());
  }

  function _awardXp(bytes32 entityId_, uint256 amount_) private {
    // Verify that this award will not going over the max.
    // If so just set the value to the max
    uint256 xp = VMInfo.getXp(entityId_) + amount_;
    uint256 max = VMGeneralTuning.getXpMax();
    if (xp > max) {
      xp = max;
    }

    // Add the XP to the voidsman
    VMInfo.setXp(entityId_, xp);
  }
}
