on:
  push:
    branches: ["main", "test"]

env:
  PROJECT_ID: rooster-ship-framework
  REGION: us-central1

jobs:
  build_packages:
    runs-on: ubuntu-latest
    steps:
      #------------------------------------------------------------------------
      # Login into Google Artifact Registry for down/up load of images
      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.ARTIFACT_SA }}

      #------------------------------------------------------------------------
      # Update Tags
      
      - name: Pull Test Wrilya Remote Image
        if: ${{ github.ref_name == 'main'}}
        run: |
          docker pull ${{env.REGION}}-docker.pkg.dev/rooster-ship-framework/wrilya:test
          docker pull ${{env.REGION}}-docker.pkg.dev/rooster-ship-framework/client:test
          docker pull ${{env.REGION}}-docker.pkg.dev/rooster-ship-framework/relayer:test

      - name: Pull Develop Wrilya Remote Image
        if: ${{ github.ref_name == 'test'}}
        run: |
          docker pull ${{env.REGION}}-docker.pkg.dev/rooster-ship-framework/wrilya:develop
          docker pull ${{env.REGION}}-docker.pkg.dev/rooster-ship-framework/client:develop
          docker pull ${{env.REGION}}-docker.pkg.dev/rooster-ship-framework/relayer:develop
      
      - name: Tag Test Wrilya Local Image as Main
        if: ${{ github.ref_name == 'main'}}
        run: |
          docker tag ${{env.REGION}}-docker.pkg.dev/rooster-ship-framework/wrilya:test ${{env.REGION}}-docker.pkg.dev/rooster-ship-framework/wrilya:main
          docker tag ${{env.REGION}}-docker.pkg.dev/rooster-ship-framework/client:test ${{env.REGION}}-docker.pkg.dev/rooster-ship-framework/client:main
          docker tag ${{env.REGION}}-docker.pkg.dev/rooster-ship-framework/relayer:test ${{env.REGION}}-docker.pkg.dev/rooster-ship-framework/relayer:main
      
      - name: Tag Develop Wrilya Local Image as Test
        if: ${{ github.ref_name == 'test'}}
        run: |
          docker tag ${{env.REGION}}-docker.pkg.dev/rooster-ship-framework/wrilya:develop ${{env.REGION}}-docker.pkg.dev/rooster-ship-framework/wrilya:test
          docker tag ${{env.REGION}}-docker.pkg.dev/rooster-ship-framework/client:develop ${{env.REGION}}-docker.pkg.dev/rooster-ship-framework/client:test
          docker tag ${{env.REGION}}-docker.pkg.dev/rooster-ship-framework/relayer:develop ${{env.REGION}}-docker.pkg.dev/rooster-ship-framework/relayer:test
      
      - name: Push Main Wrilya Remote Image Build Tag
        if: ${{ github.ref_name == 'main'}}
        run: |
          docker push ${{env.REGION}}-docker.pkg.dev/rooster-ship-framework/wrilya:main
          docker push ${{env.REGION}}-docker.pkg.dev/rooster-ship-framework/wrilya:main
          docker push ${{env.REGION}}-docker.pkg.dev/rooster-ship-framework/wrilya:main

      - name: Push Test Wrilya Remote Image Build Tag
        if: ${{ github.ref_name == 'test'}}
        run: |
          docker push ${{env.REGION}}-docker.pkg.dev/rooster-ship-framework/wrilya:test
          docker push ${{env.REGION}}-docker.pkg.dev/rooster-ship-framework/wrilya:test
          docker push ${{env.REGION}}-docker.pkg.dev/rooster-ship-framework/wrilya:test