on:
  push:
    branches: ["develop"]

env:
  PROJECT_ID: rooster-ship-framework
  REGION: us-central1

jobs:
  build_packages:
    runs-on: ubuntu-latest
    steps:
      #------------------------------------------------------------------------
      # Setup Elxiir and Erlang Environment
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '27.0'
          elixir-version: '1.17.1'

      #------------------------------------------------------------------------
      # Setup PNPM Environment
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install PNPM files
        run: pnpm install

      #------------------------------------------------------------------------
      # Login into Google Artifact Registry for down/up load of images
      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.ARTIFACT_SA }}

      #------------------------------------------------------------------------
      # Build Images

      # Prep Oban as a licensed package

      - name: Authorize Oban
        run: |
          mix hex.repo add oban https://getoban.pro/repo \
            --fetch-public-key SHA256:4/OSKi0NRF91QVVXlGAhb/BIMLnK8NHcx/EWs+aIWPc \
            --auth-key ${{secrets.OBAN_LICENSE_KEY}}
      
      # Build the Contracts Before the images so we have a local copy to package
      - name: Build Contracts 
        run: cd packages/contracts && make build

      # Build all the Service Images.
      - name: Build Images 
        run: make build.service SHA=${{github.sha}} BUILD=${{github.ref_name}}

