on:
  push:
    branches: ["develop", "15-cicd-builds"]

env:
  PROJECT_ID: rooster-ship-framework
  REGION: us-central1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '27.0'
          elixir-version: '1.17.1'
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.ARTIFACT_SA }}
      - name: Authorize Oban
        run: |
          mix hex.repo add oban https://getoban.pro/repo \
            --fetch-public-key SHA256:4/OSKi0NRF91QVVXlGAhb/BIMLnK8NHcx/EWs+aIWPc \
            --auth-key ${{secrets.OBAN_LICENSE_KEY}}
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Install PNPM files
        run: pnpm install
      - run: make build.service