on:
  push:
    branches: ["develop", "15-cicd-builds"]

env:
  PROJECT_ID: rooster-ship-framework
  REGION: us-central1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '27.0'
          elixir-version: '1.17.1'

      - name: Authenticate to Google Cloud
        id: auth 
        uses: "google-github-actions/auth@v1"
        with:
          token_format: access_token
          credentials_json: "${{ secrets.ARTIFACT_SA }}"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
      - name: "Use gcloud CLI"
        run: "gcloud info"
      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.ARTIFACT_SA }}

      - run: make build.service